ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.ApplicationKt.module

  jwt:
    issuer: "http://0.0.0.0:8080"
    audience: "artistas-app"
    secret: ${JWT_SECRET}      # usa variable de entorno; si no existe → error
    validityMs: 3600000

  db:
    url: "jdbc:h2:file:./data/tesis-db;MODE=PostgreSQL"
    user: "sa"
    password: ""
    driver: "org.h2.Driver"

#  "MI-CLAVE-SUPER-SECRETA"