ktor:
  deployment:
    port: 8080

  application:
    modules:
      - com.example.ApplicationKt.module

  jwt:
    issuer: "http://146.83.198.35:1699"
    audience: "artistas-app"
    secret: ${JWT_SECRET}
    validityMs: 3600000

  db:
    url:      ${?DATABASE_URL}
    user:     ${?DB_USER}
    password: ${?DB_PASS}
    driver:   "org.postgresql.Driver"